services:
  backend:
    build: .
    container_name: backend-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge
